[project]
name = "02-gpu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13" 
dependencies = [
    "ruff>=0.12.5",
    "cuml-cu12",
    "cudf-cu12",
]
